### ISSUE TITLE
有报错

### ISSUE THREAD

**Issue by qialie** [guoapeng/gosms#1]
../github.com/guoapeng/gosms/sender.go:57:44: multiple-value uuid.NewV4() in single-value context

**Comment by guoapeng** [comment]
hi qialie, could you post more details like exception stack for investigation and your go version please.
sice this project is built and tested on go version 12.  please try to us go version 1.12 and have a try.

**Comment by qialie** [comment]
go version is 1.13



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: guoapeng <notifications@github.com&gt;
发送时间: 2019年10月6日 21:03
收件人: guoapeng/gosms <gosms@noreply.github.com&gt;
抄送: qialie <yangcuiwang@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[guoapeng/gosms] 有报错 (#1)




hi qialie, could you post more details like exception stack for investigation and your go version please.
 sice this project is built and tested on go version 12.  please try to us go version 1.12 and have a try.

**Comment by guoapeng** [comment]
first of all , thanks for your quick reply. but could you check which depedency you are using for package uuid. we are expecting the packge from github.com/satori/go.uuid v1.2.0. and I checked the history of uuid.NewV4() and found that it's imposible to return multiple values in any version of this package. I think it's much related with your local env, and I should also ensure the code work in a complicated env. so could you please dig deeper to the issue to get more information for fixing the issue or let me know if you've solved in any way.

**Comment by guoapeng** [comment]
I replaced the package uuid with a alias to avoid overriding by any package with same name in version v1.0.4, please upgrade the version and try again.

**Comment by qialie** [comment]
thx



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: guoapeng <notifications@github.com&gt;
发送时间: 2019年10月8日 19:15
收件人: guoapeng/gosms <gosms@noreply.github.com&gt;
抄送: qialie <yangcuiwang@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[guoapeng/gosms] 有报错 (#1)




I replaced the package uuid with a alias to avoid overriding by any package with same name in version v1.0.4, please upgrade the version and try again.
